export enum CalloutState {
  SUBMITTED = 'SUBMITTED',
  WAITING_CUSTOMER_SELECTION = 'WAITING_CUSTOMER_SELECTION',
  WAITING_FOR_PROFESSIONAL = 'WAITING_FOR_PROFESSIONAL',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
}
